[General]
xml_template_path = "/path/to/xml/templates"
base_disk_path = "/path/to/base/disks"
xml_output_dir = "/path/to/xml/output"
disk_output_dir = "/path/to/disk/output"

[[Server]]
name = "Server1"
gateway = "192.168.1.1"

[[Server.Interface]]
bridge = "br0"
ip = "192.168.1.2"
mask = "255.255.255.0"

[[Server.Interface]]
bridge = "br1"
ip = "192.168.2.2"
mask = "255.255.255.0"

[[Router]]
name = "Router1"

[[Router.Interface]]
bridge = "br0"
ip = "10.0.0.1"
mask = "255.255.255.0"

[[Router.RouteRule]]
destination = "192.168.1.0"
via = "10.0.0.2"