[General]
xml_template_path = "data/base-vm.xml"
base_disk_path = "data/base-image.qcow2"
xml_output_dir = "build/xml_files"
disk_output_dir = "build/image_files"
network_config_output_dir = "build/network_config_files"

##############################
#          Servers           #
##############################

[[Server]]
name = "Server"
gateway = "10.0.0.2"

[[Server.Interface]]
id = "eth0"
bridge = "br_server"
ip = "10.0.0.1"
mask = "255.255.255.0"
mac = "00:00:00:00:10:01"

##############################
#          Routers           #
##############################

[[Router]]
name = "Router D"

[[Router.Interface]]
id = "eth0"
bridge = "br_server"
ip = "10.0.0.2"
mask = "255.255.255.0"
mac = "00:00:00:00:10:02"

[[Router.Interface]]
id = "eth1"
bridge = "br_c_d"
ip = "10.1.0.1"
mask = "255.255.255.252"
mac = "00:00:00:00:10:03"

[[Router.RouteRule]]
destination = "10.0.0.0/24"
via = "10.0.0.2"

[[Router.RouteRule]]
destination = "0.0.0.0/0"
via = "10.1.0.1"

[[Router]]
name = "Router C"

[[Router.Interface]]
id = "eth0"
bridge = "br_c_d"
ip = "10.1.0.2"
mask = "255.255.255.252"
mac = "00:00:00:00:10:04"

[[Router.Interface]]
id = "eth1"
bridge = "br_a_c"
ip = "10.2.0.2"
mask = "255.255.255.252"
mac = "00:00:00:00:10:05"

[[Router.Interface]]
id = "eth2"
bridge = "br_b_c"
ip = "10.3.0.2"
mask = "255.255.255.252"
mac = "00:00:00:00:10:06"

[[Router.RouteRule]]
destination = "10.0.0.0/24"
via = "10.1.0.0"

[[Router.RouteRule]]
destination = "10.0.1.0/24"
via = "10.2.0.2"

[[Router.RouteRule]]
destination = "10.0.2.0/24"
via = "10.2.0.2"

[[Router.RouteRule]]
destination = "10.0.3.0/24"
via = "10.3.0.2"

[[Router.RouteRule]]
destination = "10.0.4.0/24"
via = "10.3.0.2"

[[Router]]
name = "Router A"

[[Router.Interface]]
id = "eth0"
bridge = "br_a_c"
ip = "10.2.0.1"
mask = "255.255.255.252"
mac = "00:00:00:00:10:07"

[[Router.Interface]]
id = "eth1"
bridge = "br_a_pc1"
ip = "10.0.1.2"
mask = "255.255.255.0"
mac = "00:00:00:00:10:08"

[[Router.Interface]]
id = "eth2"
bridge = "br_a_pc2"
ip = "10.0.2.2"
mask = "255.255.255.0"
mac = "00:00:00:00:10:09"

[[Router.RouteRule]]
destination = "10.0.1.0/24"
via = "10.0.1.2"

[[Router.RouteRule]]
destination = "10.0.2.0/24"
via = "10.0.2.2"

[[Router.RouteRule]]
destination = "0.0.0.0/0"
via = "10.2.0.1"

[[Router]]
name = "Router B"

[[Router.Interface]]
id = "eth0"
bridge = "br_b_c"
ip = "10.3.0.1"
mask = "255.255.255.252"
mac = "00:00:00:00:10:10"

[[Router.Interface]]
id = "eth1"
bridge = "br_b_pc3"
ip = "10.0.3.2"
mask = "255.255.255.0"
mac = "00:00:00:00:10:11"

[[Router.Interface]]
id = "eth2"
bridge = "br_b_pc4"
ip = "10.0.4.2"
mask = "255.255.255.0"
mac = "00:00:00:00:10:12"

[[Router.RouteRule]]
destination = "10.0.3.0/24"
via = "10.0.3.2"

[[Router.RouteRule]]
destination = "10.0.4.0/24"
via = "10.0.4.2"

[[Router.RouteRule]]
destination = "0.0.0.0/0"
via = "10.3.0.1"

##############################
#            PCs             #
##############################

[[Server]]
name = "PC 1"
gateway = "10.0.1.2"

[[Server.Interface]]
id = "eth0"
bridge = "br_a_pc1"
ip = "10.0.1.1"
mask = "255.255.255.0"
mac = "00:00:00:00:10:13"

[[Server]]
name = "PC 2"
gateway = "10.0.2.2"

[[Server.Interface]]
id = "eth0"
bridge = "br_a_pc2"
ip = "10.0.2.1"
mask = "255.255.255.0"
mac = "00:00:00:00:10:14"

[[Server]]
name = "PC 3"
gateway = "10.0.3.2"

[[Server.Interface]]
id = "eth0"
bridge = "br_b_pc3"
ip = "10.0.3.1"
mask = "255.255.255.0"
mac = "00:00:00:00:10:15"

[[Server]]
name = "PC 4"
gateway = "10.0.4.2"

[[Server.Interface]]
id = "eth0"
bridge = "br_b_pc4"
ip = "10.0.4.1"
mask = "255.255.255.0"
mac = "00:00:00:00:10:16"
